import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import type { Metadata } from "next";
import Nevbar from './component/Navbar'
import Footer from './component/Footer'
import {Poppins} from 'next/font/google'


const poppin=Poppins({
  weight:"500",
  style:"normal",
  subsets:["latin"],
  display:"swap"
  
})

import localFont from "next/font/local";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" className={poppin.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
          <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
       
        <Nevbar />
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  );
}
